name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  Checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  DockerLogin:
    runs-on: ubuntu-latest
    needs: Checkout

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  SetImageVariables:
    runs-on: ubuntu-latest
    needs: DockerLogin

    steps:
      - name: Set Image Variables
        id: vars
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/laravel-clients"

          # Check if the event was a push to master or a tag push
          if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
            IMAGE_TAG="latest"
          else
            IMAGE_TAG="${GITHUB_REF#refs/tags/}"  # Get the tag name (e.g., v1.0.0)
          fi

          # Define tags to push
          TAGS="${IMAGE_TAG}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "TAGS=${TAGS}" >> $GITHUB_ENV

  BuildImage:
    runs-on: ubuntu-latest
    needs: SetImageVariables

    steps:
      - name: Build Docker Image
        run: |
          docker build -f ./docker/build/Dockerfile -t ${{ env.IMAGE_NAME }}:${{ env.TAGS }} .

  PushImage:
    runs-on: ubuntu-latest
    needs: BuildImage

    steps:
      - name: Push Docker Image
        run: |
          for TAG in ${{ env.TAGS }}; do
            docker push ${{ env.IMAGE_NAME }}:$TAG
          done

  TagAndPushAdditionalTags:
    runs-on: ubuntu-latest
    needs: PushImage

    steps:
      - name: Tag and Push Additional Tags
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
            docker tag ${{ env.IMAGE_NAME }}:${{ env.TAGS }} ${{ env.IMAGE_NAME }}:latest
            docker push ${{ env.IMAGE_NAME }}:latest
          fi
