name: Laravel Tests

on: [pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      meilisearch:
        image: getmeili/meilisearch:v1.5
        env:
          MEILI_MASTER_KEY: masterKey
          MEILI_NO_ANALYTICS: true
          MEILI_ENV: development
        ports:
          - 7700:7700
        options: >-
          --health-cmd="curl -f http://localhost:7700/health || exit 1"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=3
          --health-start-period=40s

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Copy .env.test
        run: php -r "file_exists('.env') || copy('.env.test', '.env');"

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm ci

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Build Vite Assets
        run: |
          npm run build

      - name: Configure Database
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_test
          DB_USERNAME: root
          DB_PASSWORD: password
          MEILISEARCH_HOST: http://127.0.0.1:7700
          MEILISEARCH_KEY: masterKey
          SCOUT_DRIVER: meilisearch
        run: |
          php artisan config:clear
          php artisan migrate

      - name: Execute tests via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_test
          DB_USERNAME: root
          DB_PASSWORD: password
          MEILISEARCH_HOST: http://127.0.0.1:7700
          MEILISEARCH_KEY: masterKey
          SCOUT_DRIVER: meilisearch
        run: php artisan test
